---
name: OpenJDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: "latest"

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run test
        run: clojure -m com.latacora.graal-empty-classpath-reproducer
